server:
  port: 8899
  cxf:
    path: /services  # 替换默认的/services路径

#springboot整合mybatis框架(mybatis总装配文件)
#加载Mybatis配置文件
#mybatis:
#  #指定 mapper 映射文件的位置
#  mapper-locations: classpath:mapper/*Mapper.xml
#  #指定sql映射文件
#  config-location: classpath:mapper/config/sqlMapConfig.xml
#  #定义别名
#  type-aliases-package: com.turbur.entity
#数据源
#spring:
#  application:
#    name: mySpringBoot
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  mvc:
#      view:
#        #页面默认前缀目录
#        prefix: /WEB-INF/pages/jsp/
#        #响应页面默认后缀
#        suffix: .jsp
#  resources:
#    static-locations: /WEB-INF/resource
#  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: rabbit
#    password: rabbit

