server:
  port: 8080

#springboot整合mybatis框架(mybatis总装配文件)
#加载Mybatis配置文件
mybatis:
  #指定 mapper 映射文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #指定sql映射文件
  config-location: classpath:mapper/config/sqlMapConfig.xml
  #定义别名
  type-aliases-package: com.turbur.entity
#数据源
spring:
  application:
    name: mySpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123654
  mvc:
      view:
        #页面默认前缀目录
        prefix: /WEB-INF/pages/jsp/
        #响应页面默认后缀
        suffix: .jsp